// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GameStateUpdate : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"players")]
    public global::System.Collections.Generic.List<Player> Players { get; } = new global::System.Collections.Generic.List<Player>();

}

[global::ProtoBuf.ProtoContract()]
public partial class Player : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    public uint Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"health")]
    public uint Health { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"position")]
    public Position Position { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"power")]
    public uint Power { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class Position : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"x")]
    public uint X { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"y")]
    public uint Y { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class UpdatePing : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
    public uint PlayerId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"latency")]
    public uint Latency { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClientAction : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"action")]
    public Action Action { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"direction")]
    public Direction Direction { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"latency")]
    public uint Latency { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public enum Action
{
    [global::ProtoBuf.ProtoEnum(Name = @"ACTION_UNSPECIFIED")]
    ActionUnspecified = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"MOVE")]
    Move = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"ATTACK")]
    Attack = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"PING")]
    Ping = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"UPDATE_PING")]
    UpdatePing = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"ATTACK_AOE")]
    AttackAoe = 5,
}

[global::ProtoBuf.ProtoContract()]
public enum Direction
{
    [global::ProtoBuf.ProtoEnum(Name = @"DIRECTION_UNSPECIFIED")]
    DirectionUnspecified = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"UP")]
    Up = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"DOWN")]
    Down = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"LEFT")]
    Left = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"RIGHT")]
    Right = 4,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
